name: Test Staged Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Staging Deployment
        run: echo "✅ Deployed to Staging!"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: Prod
    steps:
      - name: Production Deployment
        run: echo "✅ Deployed to Production!"
