name: Test Staged Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  issues: write
  contents: read

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Staging Deployment
        run: echo "✅ Deployed to Staging!"
  
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Request approval
        uses: thomasvjoseph/manual-approval@v1.0.1
        with:
          INPUT_TITLE: "Manual Approval Request"
          INPUT_BODY: "Please approve or reject by commenting 'yes' or 'no'."
          INPUT_ASSIGNEES: "wjaylin"
          INPUT_MIN_APPROVERS: 1
          INPUT_TIMEOUT: 1440


  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: Prod
    steps:
      - name: Production Deployment
        run: echo "✅ Deployed to Production!"
