name: Test Staged Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Staging Deployment
        run: echo "✅ Deployed to Staging!"
  
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - uses: macnev2013/manual-approval@v1.0.18
        with:
          secret: ${{ github.TOKEN }}
          approvers: wjaylin
          minimum-approvals: 1
          approval-wait: 600
          issue-title: 'Manual Approval'
          issue-body: |
            "Issue Body"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: Prod
    steps:
      - name: Production Deployment
        run: echo "✅ Deployed to Production!"
